### PR TITLE
Added error code descriptions

### PR DESCRIPTION
**Pull request by ulfwin**
Hi! One of the useful things with UWTerminal is that errors get a description. I wrote to Laird and asked for a file with descriptions for all error codes, and they were kind enough to give it to me! I added the file to the repository, and adjusted the code to automatically find the description.

With this change, blutil becomes even better than UWTerminal, in my opinion.

### CODE REVIEW

**Comment by projectgus** [comment]
Hi,

Thanks for this, it's a massive usability improvement. I just have two minor requests:

The get_errordesc() function leaks the file handle for 'f', at least until garbage collection runs, and also won't open codecs.csv if blutil.py is called from a different working directory. Could you please change it to something like:

```
blutil_dir = os.path.dirname(sys.argv[0])
with open(os.path.join(blutil_dir, 'codecs.csv')) as f:
    for line in f:
```

The second minor thing, when you asked Laird for the file did you tell them what you wanted to use it for? Although it's very factual data, the file falls under their copyright so I'd want to know that they're OK with it being used in this way. Even if they are OK with it I'd probably rather add a note to the top of the file along the lines of "# Contents Copyright (C) Laird PLC" or similar, just to make it clear we're incorporating part of their IP.

Thanks again for submitting this though, it is a really good improvement!

Cheers,


Angus

**Comment by ulfwin** [comment]
Very good points. I've sent a mail to my contact person at Laird (in fact,
I'm suggesting that they include the file with the UWterminal zip file,
since that would solve the license problem and does not require this
repository to be updated each time UWterminal is). I'll fix the leak as
well after I get an answer.

**Comment by projectgus** [comment]
Sounds great, thanks!

**Comment by ulfwin** [comment]
I got an answer from my contact person Jonathan Kaye at Laird:
"Hiya Ulf – you can use the file directly for this version – no license. In future, we can supply the zip file for new versions of UWterminal for you."

In other words we're good to go. But in any case I added the copyright note you suggested.

I also fixed the leak, and tested it. Can you take a look and see if you agree?

**Comment by projectgus** [comment]
That's excellent, thank you! :D

**Pull request merged**
